export const estados = [
  { label: 'AC', value: 'Acre' },
  { label: 'AL', value: 'Alagoas' },
  { label: 'AM', value: 'Amazonas' },
  { label: 'AP', value: 'Amapá' },
  { label: 'BA', value: 'Bahia' },
  { label: 'CE', value: 'Ceará' },
  { label: 'DF', value: 'Distrito Federal' },
  { label: 'ES', value: 'Espírito Santo' },
  { label: 'GO', value: 'Goiás' },
  { label: 'MA', value: 'Maranhão' },
  { label: 'MG', value: 'Minas Gerais' },
  { label: 'MS', value: 'Mato Grosso do Sul' },
  { label: 'MT', value: 'Mato Grosso' },
  { label: 'PA', value: 'Pará' },
  { label: 'PB', value: 'Paraíba' },
  { label: 'PE', value: 'Pernambuco' },
  { label: 'PI', value: 'Piauí' },
  { label: 'PR', value: 'Paraná' },
  { label: 'RJ', value: 'Rio de Janeiro' },
  { label: 'RN', value: 'Rio Grande do Norte' },
  { label: 'RO', value: 'Rondônia' },
  { label: 'RR', value: 'Roraima' },
  { label: 'RS', value: 'Rio Grande do Sul' },
  { label: 'SC', value: 'Santa Catarina' },
  { label: 'SE', value: 'Sergipe' },
  { label: 'SP', value: 'São Paulo' },
  { label: 'TO', value: 'Tocantins' },
];
